/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ingresso;

/**
 *
 * @author email
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupIngresso = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jIngNormal = new javax.swing.JRadioButton();
        jIngCamInf = new javax.swing.JRadioButton();
        jIngCamSup = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextPreco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextAdicionalVip = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextAdicionalSup = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextAssento = new javax.swing.JTextField();
        jIngresso = new javax.swing.JButton();
        jNovo = new javax.swing.JButton();
        jSair = new javax.swing.JButton();
        jTipoIngresso = new javax.swing.JLabel();
        jPrecoIng = new javax.swing.JLabel();
        jAssento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tipo de Ingresso");

        buttonGroupIngresso.add(jIngNormal);
        jIngNormal.setText("Normal");
        jIngNormal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jIngNormalItemStateChanged(evt);
            }
        });
        jIngNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIngNormalActionPerformed(evt);
            }
        });

        buttonGroupIngresso.add(jIngCamInf);
        jIngCamInf.setText("Camarote Inferior");
        jIngCamInf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jIngCamInfItemStateChanged(evt);
            }
        });
        jIngCamInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIngCamInfActionPerformed(evt);
            }
        });

        buttonGroupIngresso.add(jIngCamSup);
        jIngCamSup.setText("Camarote Superior");
        jIngCamSup.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jIngCamSupItemStateChanged(evt);
            }
        });

        jLabel2.setText("Valor");

        jLabel3.setText("Adicional VIP");

        jTextAdicionalVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAdicionalVipActionPerformed(evt);
            }
        });

        jLabel4.setText("Adicional Superior");

        jLabel5.setText("Assento");

        jIngresso.setText("Gerar Ingresso");
        jIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIngressoActionPerformed(evt);
            }
        });

        jNovo.setText("Novo");
        jNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNovoActionPerformed(evt);
            }
        });

        jSair.setText("Sair");
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jIngresso)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jIngNormal)
                                    .addComponent(jIngCamInf))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextAdicionalVip, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextAdicionalSup, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextAssento, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addComponent(jSair)))
                            .addComponent(jIngCamSup))
                        .addContainerGap(12, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAssento)
                    .addComponent(jPrecoIng)
                    .addComponent(jTipoIngresso))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jIngNormal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jIngCamInf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jIngCamSup)
                            .addComponent(jTextAssento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAdicionalVip, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAdicionalSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jIngresso)
                    .addComponent(jNovo))
                .addGap(18, 18, 18)
                .addComponent(jTipoIngresso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPrecoIng)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAssento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAdicionalVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAdicionalVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAdicionalVipActionPerformed

    private void jIngCamInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIngCamInfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIngCamInfActionPerformed

    private void jIngNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIngNormalActionPerformed
   
    }//GEN-LAST:event_jIngNormalActionPerformed

    private void jIngNormalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jIngNormalItemStateChanged
    if (jIngNormal.isSelected()){
        jTextAdicionalVip.setEnabled(false);
        jTextAdicionalSup.setEnabled(false);
        jTextAssento.setEnabled(false);
        jTextPreco.setEnabled(true);
    }
   
    }//GEN-LAST:event_jIngNormalItemStateChanged

    private void jIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIngressoActionPerformed
    Normal normal1=new Normal();    
    CamaroteInferior camaroteinf1=new CamaroteInferior();
    CamaroteSuperior camarotesup1=new CamaroteSuperior();
    
    if (jIngNormal.isSelected()){
        normal1.setPreco(Float.parseFloat(jTextPreco.getText()));
        jTipoIngresso.setText(String.valueOf(normal1.Imprimetipo()));
        jPrecoIng.setText("R$ "+String.valueOf(normal1.ImprimeValor()));
    }
    
    else if (jIngCamInf.isSelected()){
        camaroteinf1.setPreco(Float.parseFloat(jTextPreco.getText()));
        camaroteinf1.setAdicional(Float.parseFloat(jTextAdicionalVip.getText()));
        camaroteinf1.setLocalizacao(Integer.parseInt(jTextAssento.getText()));
        jTipoIngresso.setText(String.valueOf(camaroteinf1.Imprimetipo()));
        jPrecoIng.setText("R$ "+String.valueOf(camaroteinf1.ImprimeValorVip()));
        jAssento.setText("Assento "+String.valueOf(camaroteinf1.getLocalizacao()));
    }
    
    else if (jIngCamSup.isSelected()){
        camarotesup1.setPreco(Float.parseFloat(jTextPreco.getText()));
        camarotesup1.setAdicional(Float.parseFloat(jTextAdicionalVip.getText()));
        camarotesup1.setLocalizacao(Integer.parseInt(jTextAssento.getText()));
        camarotesup1.setAdicionalcs(Float.parseFloat(jTextAdicionalSup.getText()));
        jTipoIngresso.setText(String.valueOf(camarotesup1.Imprimetipo()));
        jPrecoIng.setText("R$ "+String.valueOf(camarotesup1.ImprimeValorCS()));
        jAssento.setText("Assento: "+String.valueOf(camarotesup1.getLocalizacao()));             
    }
    }//GEN-LAST:event_jIngressoActionPerformed

    private void jNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNovoActionPerformed
    jTextPreco.requestFocus();
    jTextPreco.setText("");
    jTextAdicionalVip.setText("");
    jTextAdicionalSup.setText("");
    }//GEN-LAST:event_jNovoActionPerformed

    private void jIngCamInfItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jIngCamInfItemStateChanged
    if (jIngCamInf.isSelected()){
        jTextAdicionalSup.setEnabled(false);
        jTextPreco.setEnabled(true);
        jTextAdicionalVip.setEnabled(true);
        jTextAssento.setEnabled(true);
    }
    }//GEN-LAST:event_jIngCamInfItemStateChanged

    private void jIngCamSupItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jIngCamSupItemStateChanged
    if (jIngCamSup.isSelected()){
        jTextPreco.setEnabled(true);
        jTextAdicionalVip.setEnabled(true);
        jTextAdicionalSup.setEnabled(true);
        jTextAssento.setEnabled(true);
    }
    }//GEN-LAST:event_jIngCamSupItemStateChanged

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
    System.exit(0);
    }//GEN-LAST:event_jSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupIngresso;
    private javax.swing.JLabel jAssento;
    private javax.swing.JRadioButton jIngCamInf;
    private javax.swing.JRadioButton jIngCamSup;
    private javax.swing.JRadioButton jIngNormal;
    private javax.swing.JButton jIngresso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jNovo;
    private javax.swing.JLabel jPrecoIng;
    private javax.swing.JButton jSair;
    private javax.swing.JTextField jTextAdicionalSup;
    private javax.swing.JTextField jTextAdicionalVip;
    private javax.swing.JTextField jTextAssento;
    private javax.swing.JTextField jTextPreco;
    private javax.swing.JLabel jTipoIngresso;
    // End of variables declaration//GEN-END:variables
}
